# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import image_cropping.fields
import members.models.member


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, null=True, quality=0, size=[400, 400], upload_to=members.models.member.get_file_name, verbose_name='Profile picture')),
                ('cropping', image_cropping.fields.ImageRatioField('profile_pic', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, verbose_name='Gender')),
                ('pref_position', models.IntegerField(choices=[(0, 'Goalkeeper'), (1, 'Goalkeeper/Defender'), (2, 'Goalkeeper/Midfielder'), (3, 'Goalkeeper/Forward'), (4, 'Defender'), (5, 'Defender/Midfielder'), (6, 'Midfielder'), (7, 'Midfielder/Forward'), (8, 'Forward'), (9, 'Not known')], default=9, verbose_name='Preferred position')),
                ('is_current', models.BooleanField(default=True)),
                ('shirt_number', models.CharField(blank=True, max_length=4)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
