# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import members.models.squad_membership


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20171006_1844'),
        ('teams', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['member', 'position', 'season'],
            },
        ),
        migrations.CreateModel(
            name='CommitteePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(choices=[('Mens', 'Mens'), ('Ladies', 'Ladies'), ('Mixed', 'Mixed')], max_length=6, verbose_name='Mens/Ladies/Mixed')),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='Used for visual ordering of the committee', verbose_name='Index')),
            ],
            options={
                'ordering': ('-gender', 'index'),
            },
        ),
        migrations.CreateModel(
            name='SquadMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['member', 'season'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_pic', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Season'),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.ClubTeam', validators=[members.models.squad_membership.validate_squad]),
        ),
        migrations.AlterUniqueTogether(
            name='committeeposition',
            unique_together=set([('gender', 'index')]),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.CommitteePosition'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='squadmembership',
            unique_together=set([('member', 'team', 'season')]),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together=set([('position', 'season')]),
        ),
    ]
