# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20171009_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='addr_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (line 2)'),
        ),
        migrations.AddField(
            model_name='member',
            name='addr_position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Address (lat/long)'),
        ),
        migrations.AddField(
            model_name='member',
            name='addr_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Address (post code)'),
        ),
        migrations.AddField(
            model_name='member',
            name='addr_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (street)'),
        ),
        migrations.AddField(
            model_name='member',
            name='addr_town',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (town)'),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, help_text='Used for medical information', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Name of person to contact in an emergency', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Phone number of person to contact in an emergency', max_length=15, null=True, verbose_name='Emergency contact phone'),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_relationship',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Partner', 'Partner'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Other', 'Other')], default='Other', help_text="The member's emergency contact's relationship to them", max_length=100, verbose_name='Emergency contact relationship'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_coach',
            field=models.BooleanField(default=False, help_text='Does this member possess a hockey coaching qualification?', verbose_name='Is a coach'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_umpire',
            field=models.BooleanField(default=False, help_text='Is this member a qualified hockey umpire (including probationer)?', verbose_name='Is an umpire'),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='E.g. allergies, etc. in case of medical treatment', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Current member'),
        ),
    ]
