# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20171101_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_coach',
            field=models.BooleanField(default=False, help_text='Does this member possess a hockey coaching qualification?', verbose_name='Coach?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Is this member currently part of the club?', verbose_name='Current'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_umpire',
            field=models.BooleanField(default=False, help_text='Is this member a qualified hockey umpire (including probationer)?', verbose_name='Umpire?'),
        ),
    ]
