# Generated by Django 2.0.1 on 2018-01-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20171107_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emergency_relationship',
            field=models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Partner', 'Partner'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Other', 'Other')], default='Other', help_text="The member's emergency contact's relationship to them", max_length=100, null=True, verbose_name='Emergency contact relationship'),
        ),
    ]
