# Generated by Django 2.0.1 on 2018-01-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180115_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_coach',
            field=models.NullBooleanField(default=False, help_text='Does this member possess a hockey coaching qualification?', verbose_name='Coach?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_umpire',
            field=models.NullBooleanField(default=False, help_text='Is this member a qualified hockey umpire (including probationer)?', verbose_name='Umpire?'),
        ),
    ]
