# Generated by Django 2.0.1 on 2018-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180115_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='known_as',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
