# Generated by Django 2.0.1 on 2018-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_known_as'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('view_personal_data', 'Can see the personal data (address, phone, email, medical notes etc) of a member'),)},
        ),
    ]
