# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import members.models.squad_membership


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180122_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadmembership', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='squadmembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadmembership', to='teams.ClubTeam', validators=[members.models.squad_membership.validate_squad]),
        ),
    ]
