# Generated by Django 2.0.9 on 2026-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20190108_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='shirt_number_hold_until',
            field=models.DateField(blank=True, help_text="If set, this member's shirt number stays reserved until this date, even if they are not a current member.", null=True, verbose_name='Hold shirt number until'),
        ),
    ]
