# Generated by Django 3.1.1 on 2020-09-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20190108_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_coach',
            field=models.BooleanField(blank=True, default=False, help_text='Does this member possess a hockey coaching qualification?', null=True, verbose_name='Coach?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_umpire',
            field=models.BooleanField(blank=True, default=False, help_text='Is this member a qualified hockey umpire (including probationer)?', null=True, verbose_name='Umpire?'),
        ),
    ]
