# Generated by Django 2.0.9 on 2020-08-15 07:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('style', models.CharField(choices=[('danger', 'Danger'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=6, verbose_name='Style')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, help_text='Optional: the date on which this announcement should start being displayed.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional: the date on which this announcement should stop being displayed.', null=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
