# Generated by Django 2.0.9 on 2020-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[('danger', 'Danger'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=8, verbose_name='Style'),
        ),
    ]
