# Generated by Django 2.0.1 on 2018-02-23 03:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0011_auto_20180220_1035'),
        ('matches', '0008_auto_20180205_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing_availability', models.CharField(choices=[('awaiting_response', 'Awaiting response'), ('available', 'Available'), ('not_available', 'Not available'), ('unsure', 'Not sure')], default='awaiting_response', max_length=20)),
                ('umpiring_availability', models.CharField(choices=[('awaiting_response', 'Awaiting response'), ('available', 'Available'), ('not_available', 'Not available'), ('unsure', 'Not sure')], default='awaiting_response', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Any additional details about this availability', null=True)),
                ('playing_availability_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='playing_availability')),
                ('umpiring_availability_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='umpiring_availability')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='matches.Match')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='members.Member')),
            ],
            options={
                'verbose_name_plural': 'match availabilities',
            },
        ),
    ]
