# Generated by Django 2.0.1 on 2018-02-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchavailability',
            options={'permissions': (('manage_umpiring_matchavailability', 'Can manage umpiring availabilities'),), 'verbose_name_plural': 'match availabilities'},
        ),
    ]
