# Generated by Django 2.0.1 on 2018-02-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchavailability',
            name='playing_availability',
            field=models.CharField(blank=True, choices=[('awaiting_response', 'Awaiting response'), ('available', 'Available'), ('not_available', 'Not available'), ('unsure', 'Not sure')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matchavailability',
            name='umpiring_availability',
            field=models.CharField(blank=True, choices=[('awaiting_response', 'Awaiting response'), ('available', 'Available'), ('not_available', 'Not available'), ('unsure', 'Not sure')], max_length=20, null=True),
        ),
    ]
