# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms
import offers.models.member_offer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, null=True, quality=0, size=[400, 100], upload_to=offers.models.member_offer.get_file_name)),
                ('url', models.URLField(blank=True, help_text='Link to an external website with more information')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('expiry', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
