# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberoffer',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
