# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('opposition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_won', models.PositiveSmallIntegerField(default=0, verbose_name='Home matches won')),
                ('home_drawn', models.PositiveSmallIntegerField(default=0, verbose_name='Home matches drawn')),
                ('home_lost', models.PositiveSmallIntegerField(default=0, verbose_name='Home matches lost')),
                ('home_gf', models.PositiveSmallIntegerField(default=0, verbose_name='Home matches - goals for')),
                ('home_ga', models.PositiveSmallIntegerField(default=0, verbose_name='Home matches - goals against')),
                ('away_won', models.PositiveSmallIntegerField(default=0, verbose_name='Away matches won')),
                ('away_drawn', models.PositiveSmallIntegerField(default=0, verbose_name='Away matches drawn')),
                ('away_lost', models.PositiveSmallIntegerField(default=0, verbose_name='Away matches lost')),
                ('away_gf', models.PositiveSmallIntegerField(default=0, verbose_name='Away matches - goals for')),
                ('away_ga', models.PositiveSmallIntegerField(default=0, verbose_name='Away matches - goals against')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opposition.Club')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.ClubTeam')),
            ],
            options={
                'ordering': ['club', 'team'],
            },
        ),
    ]
