# Generated by Django 2.0.1 on 2018-01-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opposition', '0002_clubstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='default_venue',
            field=models.ForeignKey(help_text='The venue this club usually plays at (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.Venue'),
        ),
    ]
