# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20171007_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteamseasonparticipation',
            name='blurb',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clubteamseasonparticipation',
            name='team_photo_caption',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
