# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:34
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20171007_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubteamseasonparticipation',
            name='cropping',
        ),
        migrations.AddField(
            model_name='clubteamseasonparticipation',
            name='team_photo_cropping',
            field=image_cropping.fields.ImageRatioField('team_photo', '900x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='team photo cropping'),
        ),
    ]
