# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20171009_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubteam',
            name='google_calendar_url',
            field=models.URLField(blank=True, help_text="    The URL of the Google Calendar feed for this team.        When a new team is added, a new Google Calendar feed is created by pointing Google Calendar     at the team's ical URL (the 'clubteam_ical_feed' url). The Google Calendar feed URL generated     from this is what should go in this field.", verbose_name='Google Calendar Feed URL'),
        ),
    ]
