# Generated by Django 2.0.1 on 2018-01-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_clubteam_google_calendar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteam',
            name='google_calendar_url',
            field=models.CharField(blank=True, help_text="    The URL of the Google Calendar feed for this team.        When a new team is added, a new Google Calendar feed is created by pointing Google Calendar     at the team's ical URL (the 'clubteam_ical_feed' url). The Google Calendar feed URL generated     from this is what should go in this field.", max_length=200, verbose_name='Google Calendar Feed URL'),
        ),
        migrations.AlterField(
            model_name='clubteamseasonparticipation',
            name='cup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.Cup'),
        ),
        migrations.AlterField(
            model_name='clubteamseasonparticipation',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.Division'),
        ),
        migrations.AlterField(
            model_name='teamcaptaincy',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.Season'),
        ),
    ]
