# Generated by Django 2.0.1 on 2018-07-10 04:30

from django.db import migrations
import django_resized.forms
import image_cropping.fields
import teams.models.participation


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20180117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteamseasonparticipation',
            name='team_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1200, 1200], upload_to=teams.models.participation.get_file_name, verbose_name='Team photo'),
        ),
        migrations.AlterField(
            model_name='clubteamseasonparticipation',
            name='team_photo_cropping',
            field=image_cropping.fields.ImageRatioField('team_photo', '1200x1200', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='team photo cropping'),
        ),
    ]
