# Generated by Django 2.0.9 on 2019-09-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_add_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteam',
            name='ordinal',
            field=models.CharField(choices=[('T1', '1sts'), ('T2', '2nds'), ('T3', '3rds'), ('T4', '4ths'), ('T5', '5ths'), ('T6', '6ths'), ('T7', '7ths'), ('T8', '8ths'), ('T9', '9ths'), ('T10', '10ths'), ('T11', '11ths'), ('T12', '12ths'), ('TMVets', "Men's Vets"), ('TLVets', "Ladies' Vets"), ('TMIndoor', "Men's Indoor"), ('TLIndoor', "Ladies' Indoor"), ('TOther', 'Other')], max_length=10, verbose_name='Team ordinal (1sts/2nds etc)'),
        ),
        migrations.AlterField(
            model_name='teamcaptaincy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamcaptaincy', to='members.Member'),
        ),
    ]
