# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Full club training', max_length=100)),
                ('datetime', models.DateTimeField(verbose_name='Training date/time')),
                ('duration_mins', models.PositiveSmallIntegerField(default=120, verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Status')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Venue')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together=set([('description', 'datetime')]),
        ),
    ]
