# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentCategory'),
        ),
    ]
