# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20171113_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentCategory'),
        ),
    ]
