# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 14:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20171113_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
