# Generated by Django 2.0.9 on 2020-10-11 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20180117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
