# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, unique=True, verbose_name='Cup Name')),
                ('gender', models.CharField(choices=[('Mens', 'Mens'), ('Ladies', 'Ladies'), ('Mixed', 'Mixed')], max_length=6, verbose_name='Mens/Ladies')),
            ],
            options={
                'verbose_name': 'cup competition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Division Name')),
                ('gender', models.CharField(choices=[('Mens', 'Mens'), ('Ladies', 'Ladies'), ('Mixed', 'Mixed')], max_length=6, verbose_name='Division gender (mens/ladies)')),
            ],
            options={
                'ordering': ['league', 'gender', 'name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, unique=True, verbose_name='League Name')),
                ('url', models.URLField(blank=True, help_text="The club's website (if it has one)", verbose_name='League Website')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(help_text='(Approx) first day of the season', verbose_name='Season start')),
                ('end', models.DateField(help_text='(Approx) last day of the season', verbose_name='Season end')),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['start'],
                'get_latest_by': 'start',
            },
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(help_text='The league that is responsible for this division', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.League'),
        ),
        migrations.AddField(
            model_name='cup',
            name='league',
            field=models.ForeignKey(blank=True, help_text='The league, if any, that oversees this cup competition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.League'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('name', 'league', 'gender')]),
        ),
    ]
