# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorsContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('mailing_list', models.BooleanField(default=False, help_text="If you select 'yes', we'll add you to our club mailing list. Don't worry - its easy to unsubscribe too!", verbose_name='Add to mailing list')),
                ('child_name', models.CharField(max_length=255)),
                ('child_age', models.CharField(choices=[('A6', '6'), ('A7', '7'), ('A8', '8'), ('A9', '9'), ('A10', '10'), ('A11', '11'), ('A12', '12'), ('A13', '13'), ('A14', '14'), ('AGT14', '> 14')], default='A6', max_length=10)),
                ('child_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('message', models.TextField(blank=True, help_text='Message (comments/questions etc)', verbose_name='Message')),
                ('our_notes', models.TextField(blank=True, help_text='Any notes from the club about this enquiry')),
                ('trigger', models.CharField(choices=[('not_selected', '-- Select --'), ('web_search', 'Web search (e.g. Google)'), ('social_media', 'Social media'), ('school_notice', 'School notice'), ('promotional_flyer', 'Promotional flyer'), ('advertising_banner', 'Advertising banner'), ('word_of_mouth', 'Word of mouth'), ('other', 'Other')], default='not_selected', max_length=30)),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date submitted')),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
    ]
