# Generated by Django 2.0.1 on 2018-05-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180117_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cshcuser',
            options={'permissions': (('can_annotate', 'Can access UI annotation tools (provided by hypothesis.is)'),)},
        ),
    ]
