# Generated by Django 2.0.9 on 2019-09-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180515_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cshcuser',
            options={'verbose_name': 'CSHC user', 'verbose_name_plural': 'CSHC users'},
        ),
        migrations.AlterField(
            model_name='juniorscontactsubmission',
            name='child_age',
            field=models.CharField(choices=[('A6', '6'), ('A7', '7'), ('A8', '8'), ('A9', '9'), ('A10', '10'), ('A11', '11'), ('A12', '12'), ('A13', '13'), ('A14', '14'), ('A15', '15'), ('A16', '16')], default='A6', max_length=10),
        ),
    ]
