# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pre_match_hype',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Pre-match hype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='report_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Match report'),
        ),
    ]
