# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20171008_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='_pre_match_hype_excerpt',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='_report_body_excerpt',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='pre_match_hype',
            field=model_utils.fields.SplitField(blank=True, no_excerpt_field=True, verbose_name='Pre-match hype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='report_body',
            field=model_utils.fields.SplitField(blank=True, no_excerpt_field=True, verbose_name='Match report'),
        ),
    ]
