# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20171122_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalking',
            name='vets_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goals for the Vets team'),
        ),
        migrations.AddField(
            model_name='goalking',
            name='vets_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Own goals for the Vets team'),
        ),
    ]
