# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 05:12
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20171122_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date', 'time', 'our_team__position'], 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='pre_match_hype',
            field=model_utils.fields.SplitField(blank=True, no_excerpt_field=True, null=True, verbose_name='Pre-match hype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='report_body',
            field=model_utils.fields.SplitField(blank=True, no_excerpt_field=True, null=True, verbose_name='Match report'),
        ),
    ]
