# Generated by Django 2.0.1 on 2018-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20180115_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='report_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Match report title'),
        ),
    ]
