# Generated by Django 2.0.9 on 2018-11-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20180205_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalking',
            name='l5_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goals for Ladies 5ths'),
        ),
        migrations.AddField(
            model_name='goalking',
            name='l5_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Own goals for Ladies 5ths'),
        ),
    ]
