# Generated by Django 2.0.9 on 2018-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20181116_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='green_card_count',
            field=models.IntegerField(blank=True, default=0, help_text='The number of green cards the player received in the match', null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='yellow_card_count',
            field=models.IntegerField(blank=True, default=0, help_text='The number of yellow cards the player received in the match', null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='red_card',
            field=models.NullBooleanField(default=False, help_text='Did the player receive a red card in the match?'),
        ),
    ]
