# Generated by Django 2.0.9 on 2018-11-19 04:52

from django.db import migrations

def integerify_cards(apps, schema_editor):
    # We can't import the Appearance model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Appearance = apps.get_model('matches', 'Appearance')
    for app in Appearance.objects.all():
        if app.green_card is None:
            app.green_card_count = None
        else:
            app.green_card_count = 1 if app.green_card else 0
        if app.yellow_card is None:
            app.yellow_card_count = None
        else:
            app.yellow_card_count = 1 if app.yellow_card else 0
        app.save()

class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20181119_1151'),
    ]

    operations = [
        migrations.RunPython(integerify_cards),
    ]
