# Generated by Django 2.0.9 on 2018-11-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20181119_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='green_card',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='yellow_card',
        ),
    ]
