# Generated by Django 2.0.9 on 2019-02-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_auto_20181119_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalking',
            old_name='vets_goals',
            new_name='mv_goals',
        ),
        migrations.RenameField(
            model_name='goalking',
            old_name='vets_own_goals',
            new_name='mv_own_goals',
        ),
    ]
