# Generated by Django 2.0.9 on 2019-07-29 09:00

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_auto_20190226_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='report_body',
            field=model_utils.fields.SplitField(blank=True, default='', no_excerpt_field=True, verbose_name='Match report'),
        ),
    ]
