# Generated by Django 2.0.9 on 2019-07-29 09:18

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_auto_20190729_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pre_match_hype',
            field=model_utils.fields.SplitField(blank=True, default='', no_excerpt_field=True, verbose_name='Pre-match hype'),
        ),
    ]
