# Generated by Django 2.0.9 on 2019-08-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_rename_indoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalking',
            name='lind_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Goals for the Ladies' Indoor team"),
        ),
        migrations.AddField(
            model_name='goalking',
            name='lind_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Own goals for the Ladies' Indoor team"),
        ),
        migrations.AddField(
            model_name='goalking',
            name='lv_goals',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Goals for the Ladies' Vets team"),
        ),
        migrations.AddField(
            model_name='goalking',
            name='lv_own_goals',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Own goals for the Ladies' Vets team"),
        ),
        migrations.AlterField(
            model_name='goalking',
            name='mind_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Goals for the Men's Indoor team"),
        ),
        migrations.AlterField(
            model_name='goalking',
            name='mind_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Own goals for the Men's Indoor team"),
        ),
        migrations.AlterField(
            model_name='goalking',
            name='mv_goals',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Goals for the Men's Vets team"),
        ),
        migrations.AlterField(
            model_name='goalking',
            name='mv_own_goals',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name="Own goals for the Men's Vets team"),
        ),
    ]
