# Generated by Django 2.0.9 on 2019-09-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_auto_20190831_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalking',
            name='m6_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goals for Mens 6ths'),
        ),
        migrations.AddField(
            model_name='goalking',
            name='m6_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Own goals for Mens 6ths'),
        ),
    ]
