# Generated by Django 2.0.9 on 2020-01-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_auto_20190917_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalking',
            name='l6_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goals for Ladies 6ths'),
        ),
        migrations.AddField(
            model_name='goalking',
            name='l6_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Own goals for Ladies 6ths'),
        ),
    ]
