# Generated by Django 3.1.1 on 2020-09-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_auto_20200115_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='red_card',
            field=models.BooleanField(default=False, help_text='Did the player receive a red card in the match?', null=True),
        ),
    ]
