# Generated by Django 2.0.9 on 2020-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_auto_20201022_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalking',
            old_name='mixed_goals',
            new_name='mixedA_goals',
        ),
        migrations.RenameField(
            model_name='goalking',
            old_name='mixed_own_goals',
            new_name='mixedA_own_goals',
        ),
    ]
