# Generated by Django 2.0.9 on 2020-10-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_auto_20201022_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalking',
            name='m7_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goals for Mens 7ths'),
        ),
        migrations.AddField(
            model_name='goalking',
            name='m7_own_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Own goals for Mens 7ths'),
        ),
    ]
