# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_auto_20171007_1455'),
        ('matches', '0001_initial'),
        ('competitions', '0002_auto_20171006_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfSeasonAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Award name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndOfSeasonAwardWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardee', models.CharField(blank=True, help_text='Only use this field if the award winner is not a member', max_length=255, verbose_name='Award winner')),
                ('comment', models.TextField(help_text='Enter a short description of why this person received this award')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='awards.EndOfSeasonAward')),
                ('member', models.ForeignKey(blank=True, default=None, help_text='(Leave blank if award winner is not a member)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_endofseasonawardwinner_awards', to='members.Member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_winners', to='competitions.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Award name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchAwardWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardee', models.CharField(blank=True, help_text='Only use this field if the award winner is not a member', max_length=255, verbose_name='Award winner')),
                ('comment', models.TextField(help_text='Enter a short description of why this person received this award')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='awards.MatchAward')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_winners', to='matches.Match')),
                ('member', models.ForeignKey(blank=True, default=None, help_text='(Leave blank if award winner is not a member)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_matchawardwinner_awards', to='members.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
