# Generated by Django 2.0.1 on 2018-01-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endofseasonawardwinner',
            options={'ordering': ['-season']},
        ),
    ]
